config/routes.rb
require 'sidekiq/web'

Eightfoot::Application.routes.draw do
  root :to => 'projects#index'

  resources :repositories

  resources :issues

  resources :projects do
    member do
      get  'show_repos'
      post 'add_repos'
      get  'add_labels'
      get  'search_repos'
      get  'add_users'
      post 'add_user'
      post 'remove_user'
    end
    post :change_heading
    post :update_position
    resources :issues do
    end
  end

  resources :organizations do
    member do
      get 'regenerate_users'
    end
  end

  get 'updates' => 'updates#index'

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  resources :users
  authenticate :user do
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  has_many :labels
  has_many :issues

  validates :slug, presence: true

  def name
    slug
  end

  def labels_in_repo
    labels.collect(&:name).join(',')
  end


  # eventually we can call the below to regenerate all data we need, only when we know it has changed (e.g., webhook)
  # TODO: make another method to regenerate just a specific issue
  def regenerate_issues(project, github_client)
    issues = github_client.list_issues(self.slug, per_page: 100)

    next_request = github_client.last_response.rels[:next]
    while next_request do
      req = next_request.get
      issues +=  req.data
      next_request = req.rels[:next]
    end

    # now persist all the issues we got
    issues.each do |i|
      issue = Issue.find_or_create_by(gh_id: i.id, project_id: project.id, repository_id: self.id)
      # copy data from the API into our issue
      issue.assignee = i.try(:assignee).try(:login)
      issue.title = i.title
      issue.comments_count = i.comments.to_i
      issue.source = i.rels[:html].href

      i.labels.each do |l|
        label = Label.find_or_create_by(name: l.name, repository_id: self.id)
        issue.labels << label if !issue.labels.include? label
        label.update_attributes(color: l.try(:color))
      end

      if issue.assignee # try to associate it to a copy of our user object, if such an object exists
        user = User.find_by_nickname(issue.assignee)
        if user
          user.issues << issue
        end
      end
      issue.save
      user.save if user
    end
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: [:show, :edit, :update, :destroy]

  def index
    @repositories = Repository.all
  end

  def show
  end

  def new
    @repository = Repository.new
  end

  def edit
  end

  def create
    @repository = Repository.new(repository_params)

    respond_to do |format|
      if @repository.save
        format.html { redirect_to @repository, notice: 'Repository was successfully created.' }
        format.json { render action: 'show', status: :created, location: @repository }
      else
        format.html { render action: 'new' }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @repository.destroy
    respond_to do |format|
      format.html { redirect_to repositories_url }
      format.json { head :no_content }
    end
  end

  private

  def set_repository
    @repository = Repository.find(params[:id])
  end

  def repository_params
    params[:repository]
  end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/repositories/_form.html.haml
= form_for(@repository) do |f|
  - if @repository.errors.any?
    #error_explanation
      %h2
        = pluralize(@repository.errors.count, "error")
        prohibited this repository from being saved:
      %ul
        - @repository.errors.full_messages.each do |msg|
          %li= msg
  .actions
    = f.submit

app/views/repositories/edit.html.haml
%h1 Editing repository
= render 'form'
= link_to 'Show', @repository
|
\#{link_to 'Back', repositories_path}

app/views/repositories/index.html.haml
%h1 Listing repositories
%table
  %thead
    %tr
      %th
      %th
      %th
  %tbody
    - @repositories.each do |repository|
      %tr
        %td= link_to 'Show', repository
        %td= link_to 'Edit', edit_repository_path(repository)
        %td= link_to 'Destroy', repository, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Repository', new_repository_path

app/views/repositories/new.html.haml
%h1 New repository
= render 'form'
= link_to 'Back', repositories_path

app/views/repositories/show.html.haml
- if notice
  .alert.alert-success= notice
= link_to 'Edit', edit_repository_path(@repository)
|
\#{link_to 'Back', repositories_path}