config/routes.rb
require 'sidekiq/web'

Eightfoot::Application.routes.draw do
  root :to => 'projects#index'

  resources :repositories

  resources :issues

  resources :projects do
    member do
      get  'show_repos'
      post 'add_repos'
      get  'add_labels'
      get  'search_repos'
      get  'add_users'
      post 'add_user'
      post 'remove_user'
    end
    post :change_heading
    post :update_position
    resources :issues do
    end
  end

  resources :organizations do
    member do
      get 'regenerate_users'
    end
  end

  get 'updates' => 'updates#index'

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  resources :users
  authenticate :user do
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/models/issue.rb
require 'activerecord-import'

class Issue < ActiveRecord::Base
  belongs_to :project
  belongs_to :repository

  has_many :labels, through: :issue_labels
  has_many :issue_labels

  def width
    w = super
    return 1 if w == 0 or w.nil?
    w
  end

  def height
    h = super
    return 1 if h == 0 or h.nil?
    h
  end

  def row
    r = super
    return 1 if r == 0 or r.nil?
    r
  end

  def col
    c = super
    return 1 if c == 0 or c.nil?
    c
  end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_project, only: [:index]
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  before_action :get_milestones

  def index
    # this is kind of ugly but it works
    @issue_map = {}
    @project.repositories.each do |repo|
      milestone = find_milestone(repo) if milestone_filtered?
      update_issue_map(all_issues(repo, milestone),repo) if !milestone_filtered? || milestone
    end
    @issues = @project.issues.where( :gh_id => @issue_map.values.collect {| each | each[:issue].id} )

    if params[:labels]
      @labels = params[:labels].split(",")
    else
      @labels = @project.labels.collect(&:name)
    end
  end

  def update_issue_map(issues,repo)
    existing_issues = Issue.where(gh_id: issues.collect(&:id))
    unsaved_issues = issues.select {|incoming| (existing_issues.detect {|existing| existing.gh_id==incoming.id}).nil?}
    unsaved_issues.map! {|unsaved| unsaved = Issue.new(gh_id: unsaved.id, project: @project, repository: repo)}
    Issue.import(unsaved_issues)
    existing_issues = Issue.where(gh_id: issues.collect(&:id))
    issues.each { |issue|
      found_issue = existing_issues.detect{|e| e.gh_id== issue.id}
      @issue_map[found_issue.id]={ issue: issue, repo: repo }
    }
  end

  def get_milestones
    @milestones = @project.repositories.reduce([]) do |acc, repo|
      acc + github_client.get("/repos/#{repo.slug}/milestones")
    end
    @milestones = @milestones.collect(&:title).to_set
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end

  private

  def set_project
    @project = current_user.projects.find(params[:project_id])
  end

  def set_issue
    @issue = Issue.find(params[:id])
  end

  def issue_params
    params[:issue]
  end

  def milestone_filtered?
    !(params[:milestone].nil? || params[:milestone] == "all")
  end

  def labels_for_repo(repo)
    labels = @project.labels.where(repository: repo).collect(&:name).join(',')
    # only include filters from query params, if query params exist
    labels = params[:labels] if params[:labels]

    labels
  end

  def all_issues(repo, milestone = nil)
    opts = { per_page: [100, @project.max_issues].min, sort: 'updated' }
    opts[:labels] = labels_for_repo(repo)
    opts[:milestone] = milestone if milestone
    issues = github_client.list_issues(repo.slug, opts)
    next_request = github_client.last_response.rels[:next]
    while issues.size < @project.max_issues && next_request do
      req = next_request.get
      issues +=  req.data
      next_request = req.rels[:next]
    end
    issues
  end

  def find_milestone(repo)
    milestones = github_client.get("/repos/#{repo.slug}/milestones") if milestone_filtered?
    milestone = milestones.detect{ |m| m.title == params[:milestone] } if milestone_filtered?
    milestone.number if milestone
  end

end

app/helpers/issues_helper.rb
module IssuesHelper

  def num_cols
    @issues.max_by(&:col).col
  end

  def pull_request_url(issue)
    pr = issue.try(:pull_request)

    if pr.rels[:html]
      return pr.rels[:html].href
    else
      nil
    end
  end

  def pull_request_changes_url(pr_url)
    return "#{pr_url}/files"
  end
end

app/views/issues/_form.html.haml
= form_for(@issue) do |f|
  - if @issue.errors.any?
    #error_explanation
      %h2
        = pluralize(@issue.errors.count, "error")
        prohibited this issue from being saved:
      %ul
        - @issue.errors.full_messages.each do |msg|
          %li= msg
  .actions
    = f.submit

app/views/issues/edit.html.haml
%h1 Editing issue
= render 'form'
= link_to 'Show', @issue
|
\#{link_to 'Back', issues_path}

app/views/issues/index.html.haml
- @page_title = "Issue Manager"
%p
  = link_to 'Project Summary', @project
  - if @labels.any?
    %span Prefiltering labels by:
    - @labels.each do |label|
      %span.label-badge.label.label-primary
        %span.label-text= label
        %i.remove-label-button.fa.fa-times-circle
.milestone-selector
  %span Select a milestone
  %select#milestone-selector{:name => "milestone-selector"}
    %option{:value => "all"} All
    - @milestones.each do |title|
      - if params[:milestone] == title
        %option{:selected => "selected", :value => title}= title
      - else
        %option{:value => title}= title
  %label{:for => "local-filter"}
    Filter
    %input.local-filter{:placeholder => "Quick filter issues", :type => "text", "data-filter-for" => 'issues'}
    %button#labels-button.btn.btn-sm.btn-default.label-legend-button Toggle Labels
- if @issues.size > 0
  #column_headers.column-headers
    - (1..num_cols).each do |i|
      .column-heading
        %input{:id => "col-header-#{i}", :type => "text", :value => column_header(i)}/
  .gridster
    %ul.gridster-data.local-filterable{"data-filtered-by" => "issues"}
      - col = 1
      - row = 1
      - @issues.each do |issue|
        - hash = @issue_map[issue.id]
        - i = hash[:issue]
        - repo = hash[:repo]
        - meta = i.labels.collect(&:name) + [i.try(:assignee).try(:login), i.title]
        - meta.compact!

        %li{class: "local-filterable portlet issue-repo-#{@project.repositories.index(repo) % 10}", "data-col" => issue.col, "data-row" => issue.row, "data-sizex" => issue.width, "data-sizey" => issue.height, :id => issue.id, "data-meta" => meta }
          %div{:class => "issue-label-container #{'expanded' if @project.display_labels}"}
            - i.labels.each do |label|
              .issue-label{:style => "background-color:##{label.color};", :title => label.name}= label.name
          .portlet-header
            - if user =  i.try(:assignee)
              .issue-assignee{"data-username" => user.login}
                %a{:href => "https://github.com/#{user.login}", :target => "_blank", :title => user.login}
                  %img.eightfoot-avatar{:alt => user.login, :src => user.rels[:avatar].href}/
            %span
              %span.issue-link
                %a{:href => i.rels[:html].href, :target => "_blank"}
                  %i.fa.fa-external-link
              - if i.comments.to_i > 0
                %a.comments-link{:href => i.rels[:html].href, :target => "_blank"}
                  %i.fa.fa-comments-o
                  = i.comments
              - if pr_url = pull_request_url(i)
                %a.pr-link{:href => pull_request_changes_url(pr_url), :target => "_blank"}
                  %i.fa.fa-code-fork
              %span.issue-title
                = i.title
- else
  %p No issues to display! Good job :)

app/views/issues/new.html.haml
%h1 New issue
= render 'form'
= link_to 'Back', issues_path

app/views/issues/show.html.haml
- if notice
  .alert.alert-success= notice
= link_to 'Edit', edit_issue_path(@issue)
|
\#{link_to 'Back', issues_path}