config/routes.rb
require 'sidekiq/web'

Eightfoot::Application.routes.draw do
  root :to => 'projects#index'

  resources :repositories

  resources :issues

  resources :projects do
    member do
      get  'show_repos'
      post 'add_repos'
      get  'add_labels'
      get  'search_repos'
      get  'add_users'
      post 'add_user'
      post 'remove_user'
    end
    post :change_heading
    post :update_position
    resources :issues do
    end
  end

  resources :organizations do
    member do
      get 'regenerate_users'
    end
  end

  get 'updates' => 'updates#index'

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  resources :users
  authenticate :user do
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :repositories, through: :project_repositories
  has_many :project_repositories

  has_many :labels, through: :project_labels
  has_many :project_labels
  has_many :users, through: :project_users
  has_many :project_users, :dependent => :destroy

  has_many :issues

  validates :name, presence: true
  validates :max_issues, numericality: {greater_than: 0, only_integer: true}

  def column_headers
    result = YAML::load(headers || '')
    result ? result : {}
  end

  def organizations(client)
    opts = { per_page: 100, sort: 'login' }
    orgs = []

    # get all orgs
    client.organizations.each do |gh_org|
      orgs << client.get(gh_org.rels[:self].href, opts)
    end

    # paginate over each orgs' members
    orgs.each do |org|
      clients = []
      gh_members = client.get(org.rels[:members].href)
      next_request = client.last_response.rels[:next]

      while gh_members.size && next_request
        req = next_request.get
        gh_members += req.data
        next_request = req.rels[:next]
      end
      org.members = gh_members
    end
    orgs
  end

  def detailed_users(client)
    details = []
    users.each do |u|
      details << client.user(u.nickname)
    end
    details
  end

  def invite_user(client, github_nickname)
    user_info = client.user(github_nickname)

    user = InvitedUser.find_or_initialize_by_nickname(
      :email => user_info.email,
      :image => user_info.rels[:avatar].href,
      :nickname => github_nickname,
      :uid => user_info.id,
      :name => user_info.name
    )

    user.transaction do
      user.save(:validate => false)
      self.users << user

      return self.save
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, except: [:index, :new, :create]

  def index
    @projects = current_user.projects.load
  end

  def show
    @detailed_users = @project.detailed_users(github_client)
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def change_heading
    heading = params.require(:heading).permit(:col_number, :value)
    col_number = heading['col_number']
    value = heading['value']

    current_heading_values = @project.column_headers
    current_heading_values[col_number] = value
    @project.update(headers: current_heading_values)

    render json: {}, :status => :ok
  end

  def add_labels
    @repos = @project.repositories
    @repos.each do |repo|
      repo_labels = github_client.labels("#{repo.slug}")
      repo_labels.each do |r|
        l = Label.find_or_create_by(:name => r.name, :repository => repo)
        l.save if l.changed?
      end
    end
  end

  def update_position
    if needs_refresh?
      render json: { refresh: true }, :status => :locked
    else
      issue_params = params.require(:issues)
      Issue.update(issue_params.keys, issue_params.values)
      l = LastEdit.create(:user_id => current_user.id)
      render json: {last_edit: l}, :status => :ok
    end
  end

  def add_repos
    begin
      repo_params = params.require(:repository).permit(:slug)
      gh_repo = github_client.get("repos/#{repo_params[:slug]}") if repo_params[:slug]
      if gh_repo
        @repo = Repository.create(repo_params)
        @repo.save if gh_repo
      end
    rescue
      flash[:error] = "No such repo #{params[:slug]}" unless gh_repo
    end

    redirect_to show_repos_project_path
  end

  def add_users
    @repos = @project.repositories
    @organizations = @project.organizations(github_client)
  end

  def add_user

    github_nickname = params.require(:username)

    user_added = @project.invite_user(github_client, github_nickname)

    if user_added
      render json: {}, status: :ok
    else
      render json: user.errors, status: :unprocessable_entity
    end
  end

  def remove_user
    user = User.find_by_nickname(params[:username])
    @project.users.delete(user)
    if @project.save
      render json: {}, status: :ok
    else
      render json: @project.errors, status: :unprocessable_entity
    end
  end

  def search_repos
    results = github_client.get("/search/repositories?q=#{params[:term]}")
    names = results.items.collect(&:full_name)
    respond_to do | format|
      format.json { render json: names }
    end
  end

  def show_repos
    @repos = github_client.repos
    @repos.each do |repo|
      r = Repository.find_or_create_by(:slug => repo.full_name)
      r.save if r.changed?

      r.destroy unless repo.has_issues
    end

    @repos = Repository.all
  end

  def create
    @project = Project.new(project_params)
    @project.users << current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private

  def needs_refresh?
    false
  end

  def set_project
    @project = current_user.projects.find(params[:id] || params[:project_id])
  end

  def project_params
    params.require(:project).permit(:name,
      :max_issues,
      :display_labels,
      :repository_ids => [],
      :label_ids => [])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def is_repo_in_project?(repo)
    false
  end

  def column_header(i)
    @project.column_headers[i.to_s] ? @project.column_headers[i.to_s] : ''
  end

end

app/views/projects/_form.html.haml
= bootstrap_form_for(@project) do |f|
  = f.text_field :name
  = f.number_field :max_issues
  = f.check_box :display_labels
  = f.submit "Save", {class: "btn btn-primary"}

app/views/projects/add_labels.html.haml
- @page_title = "Labels"
- @page_type = "normal-page"
.alert.alert-info
  %i.fa.fa-info-circle.fa-2x
  %span
    %strong Labels
    correspond to the labels you've added in GitHub.  You can filter your view into
    %strong Issue Manager
    by selecting the labels you're interested in below.  The Labels are per repository.
%p Select some labels to filter by
= simple_form_for @project do |f|
  - @project.repositories.each do |repo|
    %h1= repo.name
    = f.association :labels, :label_method => :name, :collection => repo.labels, :as => :check_boxes, :multiple => true
  = f.button :submit, "Submit"

app/views/projects/add_users.html.haml
- @page_title = "Add Users"

%script
  :plain
    var add_path = "/projects/#{@project.id}/add_user";
    var remove_path = "/projects/#{@project.id}/remove_user";

%h2 People from your organizations:
- @organizations.each do |org|
  .organization-header
    .organization-avatar
      %img{src: org.avatar}
    %h3= org.name
    = link_to 'Refresh users', regenerate_users_organization_path(org)
    %input.local-filter{type: "text", "data-filter-for" => 'users', placeholder: "Quick filter users"}
  %ul.user-list.local-filterable{"data-filtered-by" => "users"}
    - org.users.each do |user|
      = render partial: 'shared/user_tile', locals: {user: user, add_button: true, remove_button: false}

app/views/projects/edit.html.haml
- @page_title = "Edit"
- @page_type = "normal-page"

= render 'form'

app/views/projects/index.html.haml
- @page_title = 'Team Projects'
- @page_type = "normal-page"

= link_to 'New Project', new_project_path
%h1 Projects
- if @projects.any?
  %ul.list-group
    - @projects.each do |project|
      %li.list-group-item
        %a{href: project_path(project)}= project.name
        .project-options
          =link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_project_path(project)
          =link_to '<i class="fa fa-trash-o"></i>'.html_safe, project, method: :delete, data: { confirm: 'Are you sure?' }

- else
  %p
    No projects yet.
    %a{href: new_project_path} Add one.

app/views/projects/new.html.haml
- @page_title = 'Create a Team Project'
- @page_type = "normal-page"

= render 'form'

app/views/projects/show.html.haml
- @page_title = ""
- @page_type = "normal-page"

- if notice
  .alert.alert-success= notice
.btn-group
  %a.btn.btn-primary{href: project_issues_path(@project)} Issue Manager
  %a.btn.btn-default{href: edit_project_path(@project)}
    %i.fa.fa-pencil
    Edit Project
  %a.btn.btn-default{href: show_repos_project_path(@project)}
    %i.fa.fa-github
    Manage Repositories
  - if @project.repositories.any?
    %a.btn.btn-default{href: add_labels_project_path(@project)} Label Filters

%script
  :plain
    var add_path = "/projects/#{@project.id}/add_user";
    var remove_path = "/projects/#{@project.id}/remove_user";

%h2 Repositories in this project
- if @project.repositories.any?
  %ul.list-group
    - @project.repositories.each do |repo|
      %li.list-group-item
        %i.fa.fa-github
        %a{:href => "https://github.com/#{repo.name}", :target => "_blank"}= repo.name
- else
  %p
    You are not pulling issues from any repositories.
    %a{href: show_repos_project_path} Add some repositories.

- if @project.repositories.any?
  %h2 Repository issue filters
  - if @project.labels.any?
    %ul
      - @project.labels.each do |label|
        %li= label.name
  - else
    %p
      You're not pre-filtering your issues by any labels.
      %a{href: add_labels_project_path} Add some default filters.
%h2 Settings:
%ul.list-group
  %li.list-group-item
    Max Issues Per Repository: #{@project.max_issues}
  %li.list-group-item
    Display Labels: #{@project.display_labels}
%h2 Users with access to this project:
%ul.user-list.local-filterable
  - @detailed_users.each do |user|
    = render partial: 'shared/user_tile', locals: {user: user, remove_button: true, add_button: false}

= link_to 'Add Users', add_users_project_path(@project)

app/views/projects/show_repos.html.haml
- @page_title = "Manage Repositories".html_safe
- @page_type = "normal-page"

%div
  - if notice
    .alert.alert-success= notice
  .alert.alert-info
    %i.fa.fa-info-circle.fa-2x
    %span
      %strong Projects
      can aggregate issues across multiple GitHub repositories.  They can also set be set up to scope issues by only certain labels.
  %p
    Select which repositories you'll display in
    %strong= @project.name
  = simple_form_for @project do |f|
    = f.association :repositories, label_method: :slug,as: :check_boxes, multiple: true
    = f.button :submit, "Submit"
  - if flash[:error]
    .alert.alert-danger= h flash[:error]
  %h4 Or add a custom read-only repository
  = simple_form_for :repository, { url: 'add_repos' } do |f|
    = f.input :slug, label: false, placeholder: "username/project"
    = f.button :submit, "Add Repository"